#!/bin/sh

echo >> $1/init '
rootdev=
for i in $(cat /proc/cmdline)
do
	case $i in
	root=*)
		dev=${i#root=}
		case $dev in
			UUID=*)  rootdev=$(findfs "$dev") ;;
			LABEL=*) rootdev=$(findfs "$dev") ;;
			/dev/*)  rootdev=$dev ;;
		esac
		;;
	esac
done
set -- "$rootdev"
'
