#!/bin/sh

if ! grep etc/pkgmk.conf.d /etc/pkgmk.conf >/dev/null; then
	cat >> /etc/pkgmk.conf <<-"EOT"

		for i in /etc/pkgmk.conf.d/*.enabled
		do
		    if [ -e "$i" ]; then
		        . "$i"
		    fi
		done
	EOT
fi

if ! grep etc/pkgmk.conf.d /etc/pkgadd.conf >/dev/null ; then
	cat >> /etc/pkgadd.conf <<-"EOT"

		INSTALL ^etc/pkgmk.conf.d$ NO
	EOT
fi

if [ -d /etc/pkgmk.conf.d ]; then
	for f in /usr/lib/pkgmk.conf/*.enabled
	do
		if [ -e /etc/pkgmk.conf.d/${f##*/} ]; then
			diff -u /etc/pkgmk.conf.d/${f##*/} /usr/lib/pkgmk.conf/${f##*/}
		fi
	done
else
	mkdir /etc/pkgmk.conf.d
fi
