=pod

=head1 NAME

portdb-dl - download ports from http://crux.nu/

=head1 SYNOPSIS

portdb-dl

=head1 DESCRIPTION

B<portdb-dl> downloads all the ports and keys from http://crux.nu/portdb/ to $HOME/.cache/portdb

To see the differences between what you have installed and portdb, run:

	diff -ruN /etc/ports $HOME/.cache/portdb

=head1 SEE ALSO

ports(1)

=head1 LICENSE

Public domain

=cut
