#!/bin/sh

for src in /usr/lib/ports-contrib/*
do
	dest="/etc/ports/${src##*/}"
	if [ ! -f "$src"           ]; then continue; fi
	if [   -e "$dest.inactive" ]; then continue; fi
	if [   -e "$dest"          ]; then
		if diff -u "$dest" "$src"; then continue; fi
	fi
	cp -v "$src" "$dest"
done
