#!/bin/bash

PORTS_DIR=/usr/ports
 pref_dir="$HOME/.config/upkg/pref"
build_dir="$HOME/.cache/upkg/build"
onlynames=
   filter=cat

print_version() {
	awk -v FS== '
		$1 == "version" { version = $2 }
		$1 == "release" { release = $2 }
		END { if (version && release) print version "-" release }
	' "$1" | sed 's/\s//g'
}

[[ $1 == -n                 ]] && { onlynames=x; shift; }
[[ -t 1 && $onlynames == "" ]] && filter="column -t"

shopt -s nullglob

while read -r name inst_ver
do
	pkgfiles0=( "$build_dir/$name/Pkgfil"[e] "$pref_dir"/*/"$name/Pkgfile" "$PORTS_DIR"/*/"$name/Pkgfile" )
	readarray -t pkgfiles < <( readlink -f "${pkgfiles0[@]}" 2>/dev/null )

	if [[ -e $pkgfiles ]]
	then
		coldir=${pkgfiles%/*/*}
		new_ver=$( print_version "$pkgfiles" )
		new_ver=${new_ver:-error}
	else
		coldir=
		new_ver="missing"
	fi

	[[ $inst_ver == "$new_ver" ]] && continue
	if [[ $onlynames ]]; then
		printf '%s\n' "$name"
	else
		printf '%s %s -> %s %s\n' "$name" "$inst_ver" "$new_ver" "$coldir"
	fi
done < <(pkginfo -i) | $filter
