#!/bin/bash

keep_dir="$HOME/.local/upkg/keep"
 log_dir="$HOME/.local/upkg/log"
     ret=0

[[ -d $log_dir ]] \
	|| ( set -x; mkdir -p "$log_dir" )

for port in "${@:-$PWD}"
do
	name=${port##*/}
	inst_ver=$(pkginfo -i | awk -v "NAME=$name" '$1 == NAME { print $2; exit }')

	               sudo=
	(( $EUID )) && sudo=sudo

	( set -x ; $sudo pkgrm "$name" )
	err=$?

	printf '%(%F %T)T REMOVE %s %s (%s)\n' -1 "$name" "$inst_ver" "$err" >> "$log_dir/all"

	(( $err )) \
		&& ret=1

	[[ -f "$keep_dir/$name" ]] \
		&& rm "$keep_dir/$name"
done

exit $ret
