#!/bin/bash

 libdir=${BASH_SOURCE%/*}
rebuild=

[[ $1 == -r ]] && {
	rebuild=$1
	shift
}

(( $# == 0 )) && set -- "$PWD"

pkgfile=$(readlink -f "$1/Pkgfile")

if [[ -f $pkgfile ]]
then
	port=${pkgfile%/*}
else
	port=$("$libdir/upkg-port-dir" "$1")
	[[ $port == "" ]] \
		&& { printf 'ERROR: unknown port: %s\n' "$1" >&2 ; exit 1; }
fi

   "$libdir/upkg-mk"  $rebuild "$port" \
&& "$libdir/upkg-mk" -i        "$port" \
&& if [[ $rebuild == "" ]] ; then
	source "$libdir/upkg-keep" "$port"
fi
