#!/bin/bash

[[ -d $PORTS_DIR ]] || exit 1
cd -- "$PORTS_DIR"  || exit 1
git init -q         || exit 1

printf '%s\n' '/.update.*' '/.uportstag' > .gitignore

for g in */.git
do
	if [[ ! -e "$conf_dir/${g%/*}.git" ]]; then
		echo "ERROR: $g is present." >&2
		echo "All files in "$PORTS_DIR" will be keept under git control (git add -A)."
		echo "Repos synced with git driver (/etc/ports/*.git) will be added as git submodules."
		exit 1
	fi
done

for g in */.git
do
	rm -rf -- "$g"
done

git add -A
git config user.name  uports
git config user.email uports@upkg
git commit -q -a -m init
git tag uports-0
git submodule foreach git tag uports-0
echo uports-0 >.uportstag
